name: manual-integration-tests
on:
  workflow_dispatch:
permissions:
  actions: read
  contents: write
jobs:
  test-kornia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file : [ test_color, test_contrib, test_enhance, test_feature, test_filters, test_losses,
                 test_metrics, test_morphology, test_utils, geometry/test_bbox, geometry/test_calibration,
                 geometry/test_camera, geometry/test_conversions, geometry/test_depth, geometry/test_epipolar,
                 geometry/test_homography, geometry/test_linalg, geometry/test_solvers, geometry/test_subpix,
                 geometry/test_transform ]
        compile : [ F ]
    steps:
      - name: Checkout ivy-integration-tests
        uses: actions/checkout@v4
        with:
          path: ivy-integration-tests

      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v4
        with:
          repository: ivy-llc/ivy
          token: ${{ secrets.DEV_BOT_GENERAL_PAT }}
          path: ivy
          persist-credentials: true

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }} (${{ matrix.file }}, ${{ matrix.compile }})
          per_page: 64

      - name: Install Dependencies
        run: |
          cd ivy
          python3 -m pip install -r requirements/requirements.txt
          python3 -m pip install -r requirements/optional.txt

      - name: Run Tests
        id: tests
        run: |
          if [ "${{ steps.jobs.outputs.html_url }}" = "null" ]; then
            ivy-integration-tests/update_s2s.sh kornia ${{ matrix.file }} ${{ matrix.compile }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ secrets.IVY_API_KEY }}
          else
            ivy-integration-tests/update_s2s.sh kornia ${{ matrix.file }} ${{ matrix.compile }} ${{ steps.jobs.outputs.html_url }} ${{ secrets.IVY_API_KEY }}
          fi

      - name: Prepare Artifact Name
        id: prepare
        shell: bash
        run: |
          safe_file_name=$(echo "${{ matrix.file }}" | sed 's/\//-/g')
          echo "::set-output name=safe_file_name::$safe_file_name"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-kornia-${{ steps.prepare.outputs.safe_file_name }}-${{ matrix.compile }}
          path: ivy-integration-tests/test_results.txt

  test-transformers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file : [ test_vision ]
        compile : [ F ]
    steps:
      - name: Checkout ivy-integration-tests
        uses: actions/checkout@v4
        with:
          path: ivy-integration-tests

      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v4
        with:
          repository: ivy-llc/ivy
          token: ${{ secrets.DEV_BOT_GENERAL_PAT }}
          path: ivy
          persist-credentials: true

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }} (${{ matrix.file }}, ${{ matrix.compile }})
          per_page: 64

      - name: Install Dependencies
        run: |
          cd ivy
          python3 -m pip install -r requirements/requirements.txt
          python3 -m pip install -r requirements/optional.txt

      - name: Run Tests
        id: tests
        run: |
          if [ "${{ steps.jobs.outputs.html_url }}" = "null" ]; then
            ivy-integration-tests/update_s2s.sh transformers ${{ matrix.file }} ${{ matrix.compile }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ secrets.IVY_API_KEY }}
          else
            ivy-integration-tests/update_s2s.sh transformers ${{ matrix.file }} ${{ matrix.compile }} ${{ steps.jobs.outputs.html_url }} ${{ secrets.IVY_API_KEY }}
          fi

      - name: Prepare Artifact Name
        id: prepare
        shell: bash
        run: |
          safe_file_name=$(echo "${{ matrix.file }}" | sed 's/\//-/g')
          echo "::set-output name=safe_file_name::$safe_file_name"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-transformers-${{ steps.prepare.outputs.safe_file_name }}-${{ matrix.compile }}
          path: ivy-integration-tests/test_results.txt

  display-results:
    runs-on: ubuntu-latest
    needs:
      - test-kornia
      - test-transformers
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Display Test Results
        run: |
          python display_manual_test_results.py
