name: update-test-results
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"
permissions:
  actions: read
jobs:
  update-kornia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file : [ test_color, test_contrib, test_enhance, test_feature, test_filters, test_losses,
                 test_metrics, test_morphology, test_utils, geometry/test_bbox, geometry/test_calibration,
                 geometry/test_camera, geometry/test_conversions, geometry/test_depth, geometry/test_epipolar,
                 geometry/test_homography, geometry/test_linalg, geometry/test_solvers, geometry/test_subpix,
                 geometry/test_transform ]
        compile : [ F ]  # to also run the tests with backend_compilation, change this to: T, F
    steps:
      - name: Checkout ivy-integration-tests
        uses: actions/checkout@v4
        with:
          path: ivy-integration-tests

      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v4
        with:
          repository: ivy-llc/ivy
          token: ${{ secrets.DEV_BOT_GENERAL_PAT }}
          path: ivy
          persist-credentials: true

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }} (${{ matrix.file }}, ${{ matrix.compile }})
          per_page: 64

      - name: Run Tests
        id: tests
        run: |
          echo "html_url: ${{ steps.jobs.outputs.html_url }}"
          if [ "${{ steps.jobs.outputs.html_url }}" = "null" ]; then
            docker run --rm -v "$(pwd)":/ivy -v "$(pwd)"/.hypothesis:/.hypothesis ivyllc/ivy:latest ivy-integration-tests/update_tests.sh kornia ${{ matrix.file }} ${{ matrix.compile }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ secrets.INTEGRATION_TESTS_DB_KEY }}
          else
            docker run --rm -v "$(pwd)":/ivy -v "$(pwd)"/.hypothesis:/.hypothesis ivyllc/ivy:latest ivy-integration-tests/update_tests.sh kornia ${{ matrix.file }} ${{ matrix.compile }} ${{ steps.jobs.outputs.html_url }} ${{ secrets.INTEGRATION_TESTS_DB_KEY }}
          fi
